services:
  db:
    image: postgres:14
    container_name: user-auth-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: user-auth-service
    working_dir: /app/src
    command: >
      sh -c "mkdir -p logs &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./src/logs:/app/src/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: