name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: user_auth_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d user_auth_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_NAME: user_auth_db
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_PORT: 5432
      SECRET_KEY: test-secret-key
      DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('E-commerce-User-Authentication-Service/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r E-commerce-User-Authentication-Service/requirements.txt

      - name: Run migrations
        run: |
          cd E-commerce-User-Authentication-Service/src
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          cd E-commerce-User-Authentication-Service/src
          python manage.py test --verbosity=2
